server:
  port: 8080
eureka:
  client:
    service-url:
      #配置eureka服务器地址
      defaultZone: http://127.0.0.1:8080/eureka
    #是否将自己注册到服务中心（注册中心集群需要注册为true）
    register-with-eureka: false
    #是否需要搜索服务信息，因为自己是注册中心所以为false
    fetch-registry: false
